// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAotX49SuhEmqOnqOS_BE3XL802KnG0e3I',
    appId: '1:334245161536:web:0865c1ea56fd0f64ae4da5',
    messagingSenderId: '334245161536',
    projectId: 'votingapp-546a2',
    authDomain: 'votingapp-546a2.firebaseapp.com',
    storageBucket: 'votingapp-546a2.appspot.com',
    measurementId: 'G-M2BMF7H53Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtBQH_TrVlhtMOq_C8XzxnypJ6UDeqxeQ',
    appId: '1:334245161536:android:05f2c3264527142fae4da5',
    messagingSenderId: '334245161536',
    projectId: 'votingapp-546a2',
    storageBucket: 'votingapp-546a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD85naJ99ToywoeRzB_siomEYjfWsrh0o0',
    appId: '1:334245161536:ios:43342fe6b0efb545ae4da5',
    messagingSenderId: '334245161536',
    projectId: 'votingapp-546a2',
    storageBucket: 'votingapp-546a2.appspot.com',
    iosBundleId: 'com.example.votingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD85naJ99ToywoeRzB_siomEYjfWsrh0o0',
    appId: '1:334245161536:ios:43342fe6b0efb545ae4da5',
    messagingSenderId: '334245161536',
    projectId: 'votingapp-546a2',
    storageBucket: 'votingapp-546a2.appspot.com',
    iosBundleId: 'com.example.votingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAotX49SuhEmqOnqOS_BE3XL802KnG0e3I',
    appId: '1:334245161536:web:a1c7ebcc4d56dab1ae4da5',
    messagingSenderId: '334245161536',
    projectId: 'votingapp-546a2',
    authDomain: 'votingapp-546a2.firebaseapp.com',
    storageBucket: 'votingapp-546a2.appspot.com',
    measurementId: 'G-0X4HCQ0WD9',
  );
}
